language: objective-c
osx_image: xcode9.4.1
script:
  - swift test
before_deploy:
  - make portable_zip
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: ./portable_iblinter.zip
  skip_cleanup: true
  on:
    tags: true
